name: ecosystem_project
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pip
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - geopandas
  - contextily
  - shapely
  - scikit-learn
  - jupyter
  - pip:
      - torch
      - torchvision
      - tifffile
      - pillow
      - tqdm
